- hosts: localhost
  gather_facts: no
  tasks:
  - stat: 
      path: /usr/local/bin/kubectl
    register: kubectl_file
  - fail: msg='请下载文件,运行脚本`bash get-binaries.sh all`或者自行下载后再运行deploy.yml'
    when: not kubectl_file.stat.exists

- hosts: localhost
  gather_facts: no
  roles:
    - tls
