- name: Add the repo
  get_url:
    url: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo 
    mode: g=r,o=r
  become: yes

- yum: name=yum-utils state=present update_cache=yes

- name: get the info of the docker-ce
  yum: list=docker-ce
  register: temp_var

- set_fact: 
    docker_version: |-
      {%- set docker_version_list= temp_var.results | map(attribute='version') | list | select('search', docker.version ) | list  -%}
      {%- if docker_version_list | length == 1 -%}{{docker_version_list[0]}}
      {%- else -%}
        {%- set vmax = {'max': docker.version + '.0'} -%}
        {%- for ver in docker_version_list -%}
          {%- if vmax['max'] is version(ver, '<') -%}
            {%- set _ = vmax.update({"max": ver}) -%}
          {%- endif -%}
        {%- endfor -%}
        {{ vmax['max'] }}
      {%- endif %}

- name: Check if docker-ce-{{ docker_version }} is installed
  yum: list=docker-ce-{{ docker_version }}
  register: pkg

- name: Install docker-ce-{{ docker_version }}
  yum:
    name: docker-ce-{{ docker_version }}
  when: pkg.results | selectattr("yumstate", "match", "installed") | list | length == 0
